export const Z_INDICES = {
  ten: 10,
  nine: 9,
  eight: 8,
  seven: 7,
  six: 6,
  five: 5,
  four: 4,
  three: 3,
  two: 2,
  one: 1,
  none: 0,
  negativeOne: -1,
  negativeTwo: -2,
  negativeThree: -3,
  negativeFour: -4,
  negativeFive: -5,
  negativeSix: -6,
  negativeSeven: -7,
  negativeEight: -8,
  negativeNine: -9,
  negativeTen: -10,
};
